### ISSUE TITLE
TypeError: L.DistanceGrid is not a constructor

### ISSUE THREAD

**Issue by tap2k** [christopherpickering/react-leaflet-markercluster#16]
Getting this error at runtime. Any ideas?

**Comment by christopherpickering** [comment]
Did you install leaflet? Can you share some code?

**Comment by tap2k** [comment]
Yes Ive got leaflet working already. You can see my code and package.json
below:

import { useEffect, useState } from 'react';
import { MapContainer, Marker, Popup, TileLayer, useMap, useMapEvents } from
'react-leaflet';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import 'leaflet/dist/leaflet.css';
import 'leaflet/dist/leaflet.js';
import
'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css'
;
import 'leaflet-defaulticon-compatibility';
import
***@***.***/react-leaflet-markercluster/dist/styles.min.css';
import * as L from 'leaflet';

const tileset = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const attribution = '&copy; <a
href="http://osm.org/copyright">OpenStreetMap</a>
contributors';

export default function Mapper( {content, lat, long, zoom, itemWidth,
itemHeight } )
{
return (
<MapContainer center={lat, long]} zoom={zoom} scrollWheelZoom={true}
zoomSnap={0.1} style={{height: '100%', width: '100%'}}>
<TileLayer attribution={attribution} url={tileset} />
<MarkerClusterGroup>
{
content && content.map((contentItem, index) => {
if (contentItem.lat == null)
return;
else
return <Marker key={index} position={[contentItem.lat, contentItem.long]}>
<Popup>
<Content contentItem={contentItem} width={itemWidth} height={itemHeight} />
</Popup></Marker>;
})
}
</MarkerClusterGroup>
</MapContainer>
);
}

**Comment by christopherpickering** [comment]
Thanks, have you also installed the peer deps?
```json
"leaflet": "^1.9.3",
"leaflet.markercluster": "^1.5.3",
"react-leaflet": "^4.0.0"
```

Try to debug by starting with one of the [examples](https://github.com/christopherpickering/react-leaflet-markercluster/tree/master/.storybook/examples).
